### ISSUE TITLE
Translator plugin: handshake Timeout

### ISSUE THREAD

**Issue by OnkelTem** [logseq/logseq-plugin-samples#37]
I’m trying to run examples from the this repository. 
I fetched the repo, switched to the `logseq-a-translator` dir, ran `npm instal`, then `npm run build`.
It has successfully built the dist and I installed it in Logseq.

However, upon enabling it I receive a message:

```
ERROR: [Loader:#_ifb2iwsl4 - logseq-a-translator][8:21:38 PM] loadhandshake Timeout Error: handshake Timeout
    at file:///tmp/.mount_LogseqMcGrxd/resources/app/js/lsplugin.core.js:2:88419
    at g (file:///tmp/.mount_LogseqMcGrxd/resources/app/js/main.js:3608:419)
```

Ideas?

I also created a thread in the Discuss forum:

https://discuss.logseq.com/t/logseq-plugin-samples-repository-translator-plugin-handshake-timeout/26500

**Comment by xyhp915** [comment]
Hi @OnkelTem Please pull the latest code and rebuild to check it again :)
